import { Router } from 'express'
import { asyncHandler } from '../../../middlewares/asyncHandler'
import { authenticate } from '../../auth/middlewares/authenticate'
import { requireTeacher } from '../../auth/middlewares/authorize'
import * as controller from '../controllers/teacher-exams.controller'

const router = Router()
router.use(authenticate, requireTeacher())
router.get('/exams', asyncHandler(controller.list))
router.post('/exams', asyncHandler(controller.create))
router.post('/exams/auto-generate', asyncHandler(controller.autoGenerate))
router.get('/exams/:id', asyncHandler(controller.get))
router.put('/exams/:id', asyncHandler(controller.update))
router.put('/exams/:id/questions', asyncHandler(controller.replaceQuestions))
router.post('/exams/:id/submit', asyncHandler(controller.submit))
router.post('/exams/:id/copy', asyncHandler(controller.copy))
router.delete('/exams/:id', asyncHandler(controller.remove))
router.post('/exams/:id/distribution-lock', asyncHandler(controller.lockDistribution))
router.delete('/exams/:id/distribution-lock', asyncHandler(controller.unlockDistribution))
router.patch('/exams/:id/student-visibility', asyncHandler(controller.updateStudentVisibility))
router.get('/exams/:id/schedules', asyncHandler(controller.listSchedules))
router.post('/exams/:id/schedules', asyncHandler(controller.createSchedule))
router.put('/exams/:id/schedules/:scheduleId', asyncHandler(controller.updateSchedule))
router.post('/exams/:id/schedules/:scheduleId/cancel', asyncHandler(controller.cancelSchedule))
router.get('/exams/:id/schedules/:scheduleId/submissions', asyncHandler(controller.listSubmissions))
router.get('/exams/:id/schedules/:scheduleId/violations', asyncHandler(controller.listViolations))
router.get('/exams/:id/schedules/:scheduleId/proctoring-sessions', asyncHandler(controller.listProctoringSessions))
router.get('/exams/:id/schedules/:scheduleId/camera-report', asyncHandler(controller.cameraReport))
router.patch('/exams/:id/schedules/:scheduleId/violations/:violationId/review', asyncHandler(controller.reviewViolation))
router.post('/exams/:id/schedules/:scheduleId/submissions/:attemptId/invalidate', asyncHandler(controller.invalidateAttempt))
router.patch('/exams/:id/schedules/:scheduleId/submissions/:attemptId/grade', asyncHandler(controller.gradeSubmission))
router.patch('/exams/:id/schedules/:scheduleId/results', asyncHandler(controller.updateResultRelease))
router.get('/exam-approvals', asyncHandler(controller.listApprovals))
router.post('/exam-approvals/:id/approve', asyncHandler(controller.approve))
router.post('/exam-approvals/:id/reject', asyncHandler(controller.reject))
router.post('/proctoring/extend-time', asyncHandler(controller.extendTime))
router.get('/proctoring/schedules/:scheduleId/sessions', asyncHandler(controller.listLiveProctoringSessions))
router.get('/proctoring/schedules/:scheduleId/violations', asyncHandler(controller.listLiveProctoringViolations))
router.post('/proctoring/attempts/:attemptId/live/start', asyncHandler(controller.requestLiveCamera))
router.get('/proctoring/live/:sessionId', asyncHandler(controller.getTeacherLiveSession))
router.post('/proctoring/live/:sessionId/answer', asyncHandler(controller.submitTeacherLiveAnswer))
router.post('/proctoring/live/:sessionId/ice-candidates', asyncHandler(controller.addTeacherLiveCandidate))
router.get('/proctoring/live/:sessionId/ice-candidates', asyncHandler(controller.getTeacherLiveCandidates))
router.delete('/proctoring/live/:sessionId', asyncHandler(controller.endTeacherLiveSession))
export default router
